// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1675983214);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1676053233);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1676050461);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1675983094);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1675983334);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.firefox-view.feature-tour", "{\"screen\":\"FEATURE_CALLOUT_1\",\"complete\":false}");
user_pref("browser.firefox-view.view-count", 1);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{21a12036-2599-481a-b900-a15ff296992d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1676049611602");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1676071211602");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1676050127);
user_pref("browser.tabs.firefox-view.ui-state.recently-closed-tabs.open", false);
user_pref("browser.translation.engine", "");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"ublock0_raymondhill_net-browser-action\"],\"nav-bar\":[\"firefox-view-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"unified-extensions-area\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":18,\"newElementCount\":5}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("captivedetect.canonicalURL", "");
user_pref("devtools.debugger.remote-enabled", false);
user_pref("distribution.iniFile.exists.appversion", "109.0.1-2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "c99c8b8712b24071a892389becd966df");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20230202102351");
user_pref("extensions.lastAppVersion", "109.0.1-2");
user_pref("extensions.lastPlatformVersion", "109.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b1422502-3964-4094-af91-41e588553cb0\",\"pictureinpicture@mozilla.org\":\"a48608a5-c358-45cc-b394-cae1efb299d1\",\"screenshots@mozilla.org\":\"214ff56e-c4cb-4084-818e-b55ab2c9cad8\",\"webcompat@mozilla.org\":\"0e0110aa-ae60-49b7-849a-d053c5b8386a\",\"default-theme@mozilla.org\":\"e14cf810-bdc7-4bdf-9117-d8fabe600322\",\"addons-search-detection@mozilla.com\":\"11cbf4c1-a367-4169-9f04-7a05b13c89af\",\"wikipedia@search.mozilla.org\":\"d69d8f9a-1b3e-4fbc-b78b-08a4879281e1\",\"ddg@search.mozilla.org\":\"4965391e-0730-4a5d-b7d4-45d2f65fe88d\",\"uBlock0@raymondhill.net\":\"95d78151-75d7-48e1-9f73-be0dcedfa4fe\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1675853782);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1676034612);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20230202102351");
user_pref("media.gmp-manager.lastCheck", 1676030100);
user_pref("media.gmp-manager.lastEmptyCheck", 1676030100);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.videocontrols.picture-in-picture.video-toggle.has-used", true);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.delegation.enabled", false);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("places.database.lastMaintenance", 1675854497);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "e995f2f3-92c0-4d64-b22b-e6b954986326");
user_pref("security.tls.enable_0rtt_data", false);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.management.page.fileImport.enabled", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1675854497);
user_pref("toolkit.startup.last_success", 1676050125);
user_pref("toolkit.telemetry.cachedClientID", "c7354ce1-159a-453f-8a28-6cd29cb21a57");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.winRegisterApplicationRestart", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("webchannel.allowObject.urlWhitelist", "");
